### ISSUE TITLE
GregTech 2.4.0 compat?

### ISSUE THREAD

**Issue by Exzept1on** [htmlcsjs/htmlTech#5]

**Comment by htmlcsjs** [comment]
i should have an update pushed later today
if you could provide the crash report from it, that would be nice.

**Comment by Xikaro** [comment]
<br class="Apple-interchange-newline">
</body>
</html>---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// Surprise! Haha. Well, this is awkward.

Time: [2](https://mclo.gs/v5BRLAg#L2)022-08-19 1[3](https://mclo.gs/v5BRLAg#L3):16:08 YEKT
Description: Initializing game

java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/htmlcsjs/htmlTech/loaders/recipe/LaserEquipmentLoader.init()V @16[4](https://mclo.gs/v5BRLAg#L4): invokevirtual
  Reason:
    Type 'gregtech/api/recipes/ingredients/IntCircuitIngredient' (current frame, stack[1]) is not assignable to 'net/minecraft/item/crafting/Ingredient'
  Current Frame:
    bci: @164
    flags: { }
    locals: { }
    stack: { 'gregtech/api/recipes/builders/IntCircuitRecipeBuilder', 'gregtech/api/recipes/ingredients/IntCircuitIngredient' }
  Bytecode:
    0x0000000: b200 30b6 0036 c000 38b2 003e b200 4410
    0x0000010: 08b6 0048 c000 38b2 004b b200 4e10 08b6
    0x0000020: 0048 c000 38b2 004b b200 [5](https://mclo.gs/v5BRLAg#L5)105 b[6](https://mclo.gs/v5BRLAg#L6)00 48c0
    0x0000030: 0038 04bd 0053 5903 b200 5611 0090 b600
    0x0000040: 5c53 b600 60c0 0038 b200 6603 3204 b600
    0x0000050: 6ac0 0038 b200 [7](https://mclo.gs/v5BRLAg#L7)00[8](https://mclo.gs/v5BRLAg#L8) 2eb6 0074 c000 3810
    0x0000060: 28b6 0077 c000 38b6 007a b200 30b6 0036
    0x0000070: c000 3810 10b6 0074 c000 38b2 007d b200
    0x0000080: 8010 06b6 0048 c000 38b2 0083 b200 86b6
    0x00000[9](https://mclo.gs/v5BRLAg#L9)0: 0089 c000 38bb 008b 5904 bc0a 5903 [10](https://mclo.gs/v5BRLAg#L10)06
    0x00000a0: 4fb7 008e b600 92c0 0038 04bd 0094 5903
    0x00000b0: b200 98b2 009c b600 a053 b600 a4c0 0038
    0x00000c0: 1032 b600 77c0 0038 b600 7ab2 00a8 b400
    0x00000d0: ac3b 1ab2 00b1 a200 d2b2 00b5 b600 b8c0
    0x00000e0: 00ba b200 c01a 32b6 00c3 c000 bab2 00c6
    0x00000f0: b200 c9b6 00ca c000 ba04 bd00 9459 03b2
    0x0000100: 00ce 1ab6 00d2 c000 9453 b600 d5c0 00ba
    0x0000[11](https://mclo.gs/v5BRLAg#L11)0: 04bd 0094 5903 b200 d81a b600 d2c0 0094
    0x0000[12](https://mclo.gs/v5BRLAg#L12)0: 53b6 00d5 c000 bab2 00db b200 de1a b600
    0x0000[13](https://mclo.gs/v5BRLAg#L13)0: d2c0 00e0 b400 e307 b600 e4c0 00ba b200
    0x0000[14](https://mclo.gs/v5BRLAg#L14)0: 4bb2 00e7 1ab6 00d2 c000 e0b4 00e3 07b6
    0x0000[15](https://mclo.gs/v5BRLAg#L15)0: 00e4 c000 bab2 00ea b200 ed1a b600 d2c0
    0x0000[16](https://mclo.gs/v5BRLAg#L16)0: 00e0 b400 e3b6 00ca c000 ba04 bd00 5359
    0x0000[17](https://mclo.gs/v5BRLAg#L17)0: 03b2 00f0 1103 e8b6 005c 53b6 00f1 c000
    0x0000[18](https://mclo.gs/v5BRLAg#L18)0: bab2 00f7 1a32 b600 f9c0 00ba b200 701a
    0x0000[19](https://mclo.gs/v5BRLAg#L19)0: 2eb6 00fa c000 ba10 64b6 00fb c000 bab6
    0x00001a0: 00fc 8400 01a7 ff2d b[20](https://mclo.gs/v5BRLAg#L20)0 b5b6 00b8 c000
    0x00001b0: bab2 00c0 1007 32b6 00c3 c000 bab2 00ea
    0x00001c0: b200 ffb6 00ca c000 bab2 00c6 b200 c9b6
    0x00001d0: 00ca c000 bab2 003e b201 0[21](https://mclo.gs/v5BRLAg#L21)0 08b6 00e4
    0x00001e0: c000 bab2 004b b200 4e05 b600 e4c0 00ba
    0x00001f0: 04bd 0053 5903 b200 f011 03e8 b600 5c53
    0x0000200: b600 f1c0 00ba b201 06b6 00f9 c000 bab2
    0x0000210: 0070 1007 2eb6 00fa c000 ba10 64b6 00fb
    0x0000[22](https://mclo.gs/v5BRLAg#L22)0: c000 bab6 00fc b200 b5b6 00b8 c000 ba04
    0x0000[23](https://mclo.gs/v5BRLAg#L23)0: bd00 9459 03b2 0098 b200 9cb6 00a0 53b6
    0x0000[24](https://mclo.gs/v5BRLAg#L24)0: 00d5 c000 bab2 003e b201 0910 40b6 00e4
    0x0000[25](https://mclo.gs/v5BRLAg#L25)0: c000 bab2 010f 1040 b601 12c0 00ba b201
    0x0000[26](https://mclo.gs/v5BRLAg#L26)0: 1505 b601 12c0 00ba b201 18b2 011b b600
    0x0000[27](https://mclo.gs/v5BRLAg#L27)0: cac0 00ba b200 eab2 011e b600 cac0 00ba
    0x0000[28](https://mclo.gs/v5BRLAg#L28)0: b200 eab2 011e b600 cac0 00ba b200 eab2
    0x0000[29](https://mclo.gs/v5BRLAg#L29)0: 011e b600 cac0 00ba b200 eab2 011e b600
    0x00002a0: cac0 00ba 04bd 0053 5903 b200 f011 03e8
    0x00002b0: b600 5c53 b600 f1c0 00ba 04bd 0053 5903
    0x00002c0: b201 2111 03f0 b600 5c53 b600 f1c0 00ba
    0x00002d0: b201 25b6 00f9 c000 bab2 0070 1007 2eb6
    0x00002e0: 00fa c000 ba11 0320 b600 fbc0 00ba b600
    0x00002f0: fcb2 00b5 b600 b8c0 00ba 04bd 0094 5903
    0x0000[30](https://mclo.gs/v5BRLAg#L30)0: b201 2bb2 012f b601 3053 b600 d5c0 00ba
    0x0000[31](https://mclo.gs/v5BRLAg#L31)0: b201 33b2 0109 1040 b600 e4c0 00ba b201
    0x0000[32](https://mclo.gs/v5BRLAg#L32)0: 0f10 40b6 0112 c000 bab2 0136 05b6 0112
    0x0000[33](https://mclo.gs/v5BRLAg#L33)0: c000 bab2 0118 b201 39b6 00ca c000 bab2
    0x0000[34](https://mclo.gs/v5BRLAg#L34)0: 00ea b201 1eb6 00ca c000 bab2 00ea b201
    0x0000[35](https://mclo.gs/v5BRLAg#L35)0: 1eb6 00ca c000 bab2 00ea b201 1eb6 00ca
    0x0000[36](https://mclo.gs/v5BRLAg#L36)0: c000 bab2 00ea b201 1eb6 00ca c000 ba04
    0x0000[37](https://mclo.gs/v5BRLAg#L37)0: bd00 5359 03b2 00f0 1103 e8b6 005c 53b6
    0x0000[38](https://mclo.gs/v5BRLAg#L38)0: 00f1 c000 ba04 bd00 5359 03b2 0121 1103
    0x0000[39](https://mclo.gs/v5BRLAg#L39)0: f0b6 005c 53b6 00f1 c000 bab2 013d b600
    0x00003a0: f9c0 00ba b200 7010 072e b600 fac0 00ba
    0x00003b0: 1103 20b6 00fb c000 bab6 00fc b200 30b6
    0x00003c0: 0036 c000 38b2 01[40](https://mclo.gs/v5BRLAg#L40) b601 43c0 0038 b200
    0x00003d0: c6b2 00c9 b600 89c0 0038 04bd 0053 5903
    0x00003e0: b200 4e11 0240 b600 5c53 b600 60c0 0038
    0x00003f0: b201 48b6 014a c000 38b2 0070 072e b600
    0x0000400: 74c0 0038 1014 b600 77c0 0038 b600 7ab2
    0x0000[41](https://mclo.gs/v5BRLAg#L41)0: 0030 b600 36c0 0038 b201 4db2 0150 07b6
    0x0000[42](https://mclo.gs/v5BRLAg#L42)0: 0048 c000 38b2 0153 b201 56b6 0089 c000
    0x0000[43](https://mclo.gs/v5BRLAg#L43)0: 38b2 0159 b201 5cb6 0089 c000 38b2 007d
    0x0000[44](https://mclo.gs/v5BRLAg#L44)0: b201 5f07 b600 48c0 0038 b201 64b2 0167
    0x0000[45](https://mclo.gs/v5BRLAg#L45)0: b600 89c0 0038 b201 6ab6 014a c000 38b2
    0x0000[46](https://mclo.gs/v5BRLAg#L46)0: 0070 062e b600 74c0 0038 1100 c8b6 0077
    0x0000[47](https://mclo.gs/v5BRLAg#L47)0: c000 38b6 007a b1                      
  Stackmap Table:
    append_frame(@210,Integer)
    chop_frame(@424,1)

    at net.htmlcsjs.htmlTech.loaders.HTRecipeManiger.init(HTRecipeManiger.java:10)
    at net.htmlcsjs.htmlTech.proxy.CommonProxy.registerRecipes(CommonProxy.java:38)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_602_CommonProxy_registerRecipes_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
    at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:5601)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:[49](https://mclo.gs/v5BRLAg#L49)7)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by htmlcsjs** [comment]
thanks
