### ISSUE TITLE
Crash with GTCEu 2.5.0-beta

### ISSUE THREAD

**Issue by Exzept1on** [htmlcsjs/htmlTech#8]
Log: 
[crash-2023-01-25_22.53.06-client.txt](https://github.com/htmlcsjs/htmlTech/files/10501059/crash-2023-01-25_22.53.06-client.txt)

**Comment by htmlcsjs** [comment]
known, i dont know when i can get a fix out as i want to do some rewrites to the mod

**Comment by htmlcsjs** [comment]
Fixed in [`635da9e`](https://github.com/htmlcsjs/htmlTech/commit/635da9e7c7c28c66fe3671be0ea1a371a0687ead)
